machine:
  php:
    version: 5.6.38
dependencies:
  pre:
    - chmod -R 777 ~/circle-ci-cakephp/app/tmp
  post:
    - echo "<?php
        class DATABASE_CONFIG {
        public \$test = array(
          'datasource' => 'Database/Mysql',
          'persistent' => false,
          'host' => '127.0.0.1',
          'login' => 'ubuntu',
          'password' => '',
          'database' => 'circle_test',
          'prefix' => ''
        );
        }" > ~/circle-ci-cakephp/app/Config/database.php
    - cd ~/circle-ci-cakephp/app/ && composer install
test:
  override:
    - cd ~/circle-ci-cakephp/app/ && ./Console/cake test app AllTests


