version: 2
jobs:
  php_test:
    docker:
      - image: circleci/php:5.6.38-apache-jessie-node-browsers-legacy
        environment:
          DEBUG: true
          DATABASE_URL: "mysql://root:password@127.0.0.1/cisample?encoding=utf8mb4&timezone=UTC&cacheMetadata=true"
          DATABASE_TEST_URL: "mysql://root:password@127.0.0.1/cisample?encoding=utf8mb4&timezone=UTC&cacheMetadata=true"
      - image: circleci/mysql:5.7
        command: mysqld  --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        environment:
          MYSQL_DATABASE: cisample
          MYSQL_ROOT_PASSWORD: password
    working_directory: /var/www/html
    steps:
      - run:
          name: Provide permisson for circleci
          command: chown -R circleci:circleci /var/www/html
      - restore_cache:
          key: circle-ci-cakephp-{{ .Branch }}
      - checkout
      - run: composer install --dev --no-interaction
      - save_cache:
          key: circle-ci-cakephp-{{ .Branch }}
          paths:
            - "/home/ubuntu/.composer/cache"
      - run:
          name: create test repot dir
          command: mkdir -p $CIRCLE_TEST_REPORTS/phpunit
      - run:
          name: Wait for MySQL DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Initialize Database
          command: bin/cake migrations migrate
  php_code_sniffer:
    docker:
      - image: circleci/php:5.6.38-apache-jessie-node-browsers-legacy
        environment:
          DEBUG: true
    working_directory: /var/www/html
    steps:
      - run:
          name: Provide permisson for circleci
          command: sudo chown -R circleci:circleci /var/www/html
      - restore_cache:
          key: circle-ci-cakephp-{{ .Branch }}
      - checkout
      - run:
          name: Install dependency 
          command: composer install --dev --no-interaction
      - run:
          name: Install Framgia-ci tool
          command: curl -o /usr/bin/framgia-ci https://raw.githubusercontent.com/framgia/ci-report-tool/master/dist/framgia-ci && chmod +x /usr/bin/framgia-ci
      - save_cache:
          key: circle-ci-cakephp-{{ .Branch }}
          paths:
            - "/home/ubuntu/.composer/cache"
      - run:
          name: Run Framgia-ci tool
          command: framgia-ci run --local

workflows:
  version: 2
  build-all:
    jobs:
      - php_code_sniffer
      - php_test:
          requires:
            - php_code_sniffer

